/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proy.vista;

/**
 *
 */
public class VentanaMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaMenuPrincipal
     */
    public VentanaMenuPrincipal() {
        initComponents();
        iniciarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNuevaEntrada = new javax.swing.JButton();
        btnNuevaSalida = new javax.swing.JButton();
        btnReportesDeEntrada = new javax.swing.JButton();
        btnReportesDeSalida = new javax.swing.JButton();
        btnMiInventario = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        lblUsuarioActual = new javax.swing.JLabel();
        mnBarPrincipal = new javax.swing.JMenuBar();
        mnClientes = new javax.swing.JMenu();
        mnItmRegistroClientes = new javax.swing.JMenuItem();
        mnProveedores = new javax.swing.JMenu();
        mnItmProveedores = new javax.swing.JMenuItem();
        mnUsuarios = new javax.swing.JMenu();
        mnItmRegistroUsuarios = new javax.swing.JMenuItem();
        mnArchivos = new javax.swing.JMenu();
        mnItmSalir = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnNuevaEntrada.setText("Nueva Entrada");

        btnNuevaSalida.setText("Nueva Salida");

        btnReportesDeEntrada.setText("Reportes de entrada");

        btnReportesDeSalida.setText("Reportes de salida");

        btnMiInventario.setText("Mi inventario");

        lblLogo.setText("Logo Empresa");

        lblUsuarioActual.setText("Usuario Actual:");

        mnClientes.setText("Clientes");

        mnItmRegistroClientes.setText("Registro de clientes");
        mnClientes.add(mnItmRegistroClientes);

        mnBarPrincipal.add(mnClientes);

        mnProveedores.setText("Proveedores");

        mnItmProveedores.setText("Registro de proveedores");
        mnProveedores.add(mnItmProveedores);

        mnBarPrincipal.add(mnProveedores);

        mnUsuarios.setText("Usuarios");

        mnItmRegistroUsuarios.setText("Registro de usuarios");
        mnUsuarios.add(mnItmRegistroUsuarios);

        mnBarPrincipal.add(mnUsuarios);

        mnArchivos.setText("Archivo");

        mnItmSalir.setText("Cerrar sesión");
        mnArchivos.add(mnItmSalir);

        jMenuItem2.setText("Salir");
        mnArchivos.add(jMenuItem2);

        mnBarPrincipal.add(mnArchivos);

        setJMenuBar(mnBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 266, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNuevaEntrada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNuevaSalida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMiInventario))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnReportesDeEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReportesDeSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsuarioActual)
                            .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuarioActual)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMiInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReportesDeSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReportesDeEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String getUsuarioActual(){
        return usuarioActual;
    }
    
    /**
     * Inicia componentes de MenuPrincipal
     * Da el nombre al lblUsuarioActual
     * Carga el logotipo de la empresa
     * Centra el formulario al inciar
     */
    public void iniciarComponentes(){
        setLocationRelativeTo(null);

    }
    private String usuarioActual;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnMiInventario;
    public javax.swing.JButton btnNuevaEntrada;
    public javax.swing.JButton btnNuevaSalida;
    public javax.swing.JButton btnReportesDeEntrada;
    public javax.swing.JButton btnReportesDeSalida;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblUsuarioActual;
    private javax.swing.JMenu mnArchivos;
    private javax.swing.JMenuBar mnBarPrincipal;
    private javax.swing.JMenu mnClientes;
    private javax.swing.JMenuItem mnItmProveedores;
    private javax.swing.JMenuItem mnItmRegistroClientes;
    private javax.swing.JMenuItem mnItmRegistroUsuarios;
    private javax.swing.JMenuItem mnItmSalir;
    private javax.swing.JMenu mnProveedores;
    private javax.swing.JMenu mnUsuarios;
    // End of variables declaration//GEN-END:variables
}
